Repository wecode-bootcamp-korea/43-2nd-finding-maehwa-frontend, pull requests merged in 2023-04, with the labels that each got.

#19 [43기 김민경]기본 모달 레이아웃 구현
  src/Router.js
  src/components/Modal/App.js
  src/components/Modal/Modal.js
  src/components/Modal/ModalLayout.js
  src/components/Modal/ModalLayout.style.js
Labels: 멘토 리뷰 요청

#12 [43기 장지아] KakaoLogin 카카오 소셜로그인 구현
  src/Router.js
  src/config.js
  src/pages/KakaoLogin/KakaoLogin.js
  src/pages/KakaoLogin/KakaoLogin.style.js
  src/pages/KakaoLogin/KakaoLoginAuth.js
Labels: 수정사항 반영완료, 멘토 리뷰 요청

#21 [43기 김준영] Review 레이아웃 재구성
  package-lock.json
  package.json
  src/pages/Review/Comment.js
  src/pages/Review/CommentStyle.scss
  src/pages/Review/ImgModal.js
  src/pages/Review/ImgModalStyle.js
  src/pages/Review/MoreDetail.js
  src/pages/Review/Review.js
  src/pages/Review/ReviewStyle.js
Labels: Rebase 요청

#18 [43기 김준영] PlaceList 레이아웃 구현
  package-lock.json
  package.json
  public/data/placeInfoData.json
  public/images/loopy.png
  public/images/reviewmap.png
  public/images/splashImg.png
  public/images/toilet1.jpeg
  public/images/toilet2.jpeg
  public/images/toilet3.jpeg
  public/images/toilet4.png
  public/images/toilet6.png
  public/images/스크린샷 2023-03-24 오전 1.09.38.png
  src/components/PlaceList/PlaceList.js
  src/components/PlaceList/PlaceListStyle.js
Labels: 멘토 리뷰 요청

#17 [43기 김준영] Review 기능 구현
  .env
  package-lock.json
  package.json
  public/data/reviewData.json
  public/data/tagData.json
  public/images/pencil.png
  public/images/trash.png
  src/Router.js
  src/pages/Atoms.js
  src/pages/Review/Comment.js
  src/pages/Review/CommentStyle.js
  src/pages/Review/LikeComment.js
  src/pages/Review/LikeCommentStyle.js
  src/pages/Review/ModalImg.js
  src/pages/Review/Tag.js
  src/pages/Review/TagStyle.js
  src/pages/Review/WriteReview.js
  src/pages/Review/WriteReviewStyle.js
Labels: 완료

#20 [43기 김민경] 모달 컴포넌트 재사용 및 기능 구현
  public/images/filter.png
  public/images/plus2 (1).png
  public/index.html
  src/Router.js
  src/components/Modal/App.js
  src/components/Modal/Final.js
  src/components/Modal/Final.style.js
  src/components/Modal/Modal.js
  src/components/Modal/ModalLayout.style.js
  src/components/PlaceList/PlaceList.js
  src/components/PlaceList/PlaceListStyle.js
  src/components/PlaceList/PlaceModal.js
  src/components/PlaceList/PlaceModalData.js
  src/components/PlaceList/PlaceModalStyle.js
  src/components/PlaceList/PlaceModalTag.js
  src/components/Wishlist/HeartComponent.js
  src/components/Wishlist/HeartComponent.style.js
  src/pages/Atoms.js
  src/pages/Library/LIBRARYLISTIMG.js
  src/pages/Library/Library.js
  src/pages/Library/Library.style.js
  src/pages/Library/LibraryList.js
  src/pages/Library/LibraryListMap.js
  src/pages/Library/LibraryListMap.style.js
  src/pages/Wishlist/WishListMap.js
  src/pages/Wishlist/WishListMap.style.js
  src/pages/Wishlist/Wishlist.js
  src/pages/Wishlist/Wishlist.style.js
Labels: 수정사항 반영완료
